[mgr]
ratio = [1, 2, 5]
sort_by = "extension"
sort_sensitive = false
sort_reverse = false
sort_dir_first = true

[opener]
chrome = [
  { run = 'open -a "Google Chrome" "$@"', desc = "Chrome", for = "macos" }
]
md-browser = [
  { run = '~/.config/yazi/bin/md-to-browser.sh "$1"', desc = "Render markdown in Chrome", for = "macos" }
]
edit = [
  { run = 'nvim "$@"', desc = "Edit in nvim", block = true }
]

[open]
prepend_rules = [
  { url = "*.[mM][dD]",                          use = [ "edit", "md-browser" ] },
  { url = "*.[mM][aA][rR][kK][dD][oO][wW][nN]",  use = [ "edit", "md-browser" ] },
  { url = "*.[hH][tT][mM][lL]",                  use = [ "edit", "chrome", "reveal" ] }
]
